apiVersion: v1
kind: Service
metadata:
  name: {{ include "analyze-plugin-sunsetting.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "analyze-plugin-sunsetting.name" . }}
    helm.sh/chart: {{ include "analyze-plugin-sunsetting.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.appVersion }}
    app.kubernetes.io/component: analyze-plugin-sunsetting
    app.kubernetes.io/part-of: analyze
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "analyze-plugin-sunsetting.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
